# Provsioning LAB:18 enviroment
---
- name: Provsioning LAB:18 enviroment
  hosts: all
  become: yes

  tasks:

    - name: Install needed network manager libs
      package:
        name:
          - NetworkManager-glib
          - nm-connection-editor
          - libsemanage-python
          - policycoreutils-python
        state: present

    - name: Enable IPv4 forwarding on the routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: "'Router' in inventory_hostname"

    - name: Configure Team interfaces
      nmcli:
        type: team
        conn_name: '{{ item.conn_name }}'
        mode: 802.3ad
        ip4: '{{ item.ip4 }}'
        state: present
      with_items: 
        - '{{ teams }}'
      when: teams is defined

    - name: Remove connections of members of Team interfaces
      nmcli:
        conn_name: '{{ item.conn_name }}'
        state: absent
      with_items: 
        - '{{ team_members }}'
      when: team_members is defined

    - name: Configure members of Team interfaces
      nmcli:
        type: team-slave
        conn_name: '{{ item.conn_name }}'
        ifname: '{{ item.ifname }}'
        master: '{{ item.master }}'
        state: present
      with_items: 
        - '{{ team_members }}'
      when: team_members is defined

    - name: Configure Vlan sub-interfaces
      nmcli:
        type: vlan
        conn_name: '{{ item.conn_name }}'
        ifname: '{{ item.ifname }}'
        vlanid: '{{ item.vlanid }}'
        vlandev: '{{ item.vlandev }}'
        ip4: '{% if item.ip4 is defined %} {{ item.ip4 }} {% endif %}'
        state: present
      with_items: 
        - '{{ vlans }}'
      when: vlans is defined

    - name: Remove default from eth0
      shell: nmcli connection modify System\ eth0 ipv4.never-default yes && nmcli connection up System\ eth0
      when: gw is defined

    - name: Setup default route
      shell: "nmcli connection modify {{ gw.conn_name }} ipv4.gateway {{ gw.ip4 }} && nmcli connection up {{ gw.conn_name }}"
      when: gw is defined

